#!/bin/sh
cat << EOF

+++++++++++++++++++++++++++++++++++ SERVER INFO ++++++++++++++++++++++++++++++++

          Name: `cat /etc/hostname`
          Uptime: $(uptime)
          Distro: `lsb_release -s -d` with `uname -r`

          CPU Load: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
          Free Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M
          Free Disk: `df -h / | awk '{ a = $2 } END { print a }'`

          IP:`ip -4 -o addr show ens18 | awk '{print $4}'`

          Updates=$(apt list --upgradable 2>/dev/null | grep -c upgradable)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
EOF
