name: Push Changes to Template

on:
  push:
    paths:
      - 'Options.ini'

jobs:
    push:
        runs-on: proxmox
        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              env: 
                PROXMOX_API_TOKEN_ID: ${{ vars.PROXMOX_API_TOKEN_ID }}
                PROXMOX_API_URL: ${{ vars.PROXMOX_API_URL }}
                PROXMOX_HOST: ${{ vars.PROXMOX_HOST }}
                PROXMOX_HOST_NODE: ${{ vars.PROXMOX_HOST_NODE }}
                STORAGE_POOL: ${{ vars.STORAGE_POOL }}
                PROXMOX_SSH_PASSWORD: ${{ secrets.PROXMOX_SSH_PASSWORD }}
                PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN }}
                PROXMOX_PRIVATE_KEY: ${{ secrets.PROXMOX_PRIVATE_KEY }}
              run: |
                  chmod +x ./Scripts/build.sh
                  ./Scripts/build.sh                  
